name: "Docker VServerify Common Action"

description: "This action wraps up the VServerification process from a Docker Image"

inputs:
  gh_token:
    description: "The GitHub Token, value of `secrets.GITHUB_TOKEN` in the calling workflow"
    required: true
  img_name:
    description: "The image name to convert"
    required: true
  img_tag:
    description: "Tag of the image to convert"
    required: true
  conversion_type:
    description: "Type of conversion, either 'vserver' or 'template'"
    default: "vserver"
    required: true
  registry:
    description: "The registry name"
    default: "ghcr.io/croesusfin/"
    required: false


runs:
  using: "composite"
  steps:
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ inputs.gh_token }}
        registry: ghcr.io

    - name: Docker Pull, Run & Export
      shell: bash
      run: |
        img_name_tag="ghcr.io/croesusfin/${{ inputs.img_name }}:${{ inputs.img_tag }}"
        img_name_dot="${{ inputs.img_name }}-${{ inputs.img_tag }}"
        img_tar_file="${img_name_dot//./-}.tar.gz"
        img_run_name="img-${img_name_dot//./-}"
        echo "Image Run Name : ${img_run_name}"
        mkdir -p export
        docker pull ${img_name_tag}
        docker kill ${img_run_name} >/dev/null 2>&1 || true
        docker rm ${img_run_name} >/dev/null 2>&1 || true
        docker run --name ${img_run_name} ${img_name_tag} /bin/true
        docker kill ${img_run_name} >/dev/null 2>&1 || true
        docker export ${img_run_name} | gzip > export/${img_tar_file}
        docker rm ${img_run_name} >/dev/null 2>&1 || true

    - name: Transfer to qaref as reference
      if: ${{ inputs.conversion_type == 'vserver' }}
      shell: bash
      run: |
        img_name_dot="${{ inputs.img_name }}-${{ inputs.img_tag }}"
        img_tar_file="${img_name_dot//./-}.tar.gz"
        echo "Image Tar Name : ${img_tar_file}"
        scp export/${img_tar_file} qaref:/home/livraison/upload/
        ssh qaref "sudo /home/livraison/untarvref ${img_tar_file}"

    - name: Transfer to qaref as template
      if: ${{ inputs.conversion_type == 'template' }}
      shell: bash
      run: |
        img_name_dot="${{ inputs.img_name }}-${{ inputs.img_tag }}"
        img_tar_file="${img_name_dot//./-}.tar.gz"
        echo "Image Tar Name : ${img_tar_file}"
        scp export/${img_tar_file} qaref:/vref/
